# TCL File Generated by Component Editor 23.1
# Mon Dec 09 15:06:31 MST 2024
# DO NOT MODIFY


# 
# pwd_controller_avalon "pwd_controller_avalon" v1.0
#  2024.12.09.15:06:31
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pwd_controller_avalon
# 
set_module_property DESCRIPTION ""
set_module_property NAME pwd_controller_avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME pwd_controller_avalon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pwd_controller_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pwm_controller_avalon.vhd VHDL PATH ../../hdl/pwm/pwm_controller_avalon.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst reset_n Input 1


# 
# connection point export
# 
add_interface export conduit end
set_interface_property export associatedClock clock_sink
set_interface_property export associatedReset reset_sink
set_interface_property export ENABLED true
set_interface_property export EXPORT_OF ""
set_interface_property export PORT_NAME_MAP ""
set_interface_property export CMSIS_SVD_VARIABLES ""
set_interface_property export SVD_ADDRESS_GROUP ""

add_interface_port export red_out red_out Output 1
add_interface_port export green_out green_out Output 1
add_interface_port export blue_out blue_out Output 1


# 
# connection point pwd_controller_avalon0
# 
add_interface pwd_controller_avalon0 avalon end
set_interface_property pwd_controller_avalon0 addressUnits WORDS
set_interface_property pwd_controller_avalon0 associatedClock clock_sink
set_interface_property pwd_controller_avalon0 associatedReset reset_sink
set_interface_property pwd_controller_avalon0 bitsPerSymbol 8
set_interface_property pwd_controller_avalon0 burstOnBurstBoundariesOnly false
set_interface_property pwd_controller_avalon0 burstcountUnits WORDS
set_interface_property pwd_controller_avalon0 explicitAddressSpan 0
set_interface_property pwd_controller_avalon0 holdTime 0
set_interface_property pwd_controller_avalon0 linewrapBursts false
set_interface_property pwd_controller_avalon0 maximumPendingReadTransactions 0
set_interface_property pwd_controller_avalon0 maximumPendingWriteTransactions 0
set_interface_property pwd_controller_avalon0 readLatency 0
set_interface_property pwd_controller_avalon0 readWaitTime 1
set_interface_property pwd_controller_avalon0 setupTime 0
set_interface_property pwd_controller_avalon0 timingUnits Cycles
set_interface_property pwd_controller_avalon0 writeWaitTime 0
set_interface_property pwd_controller_avalon0 ENABLED true
set_interface_property pwd_controller_avalon0 EXPORT_OF ""
set_interface_property pwd_controller_avalon0 PORT_NAME_MAP ""
set_interface_property pwd_controller_avalon0 CMSIS_SVD_VARIABLES ""
set_interface_property pwd_controller_avalon0 SVD_ADDRESS_GROUP ""

add_interface_port pwd_controller_avalon0 avs_read read Input 1
add_interface_port pwd_controller_avalon0 avs_write write Input 1
add_interface_port pwd_controller_avalon0 avs_address address Input 2
add_interface_port pwd_controller_avalon0 avs_readdata readdata Output 32
add_interface_port pwd_controller_avalon0 avs_writedata writedata Input 32
set_interface_assignment pwd_controller_avalon0 embeddedsw.configuration.isFlash 0
set_interface_assignment pwd_controller_avalon0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment pwd_controller_avalon0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment pwd_controller_avalon0 embeddedsw.configuration.isPrintableDevice 0

